# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5835e54be9d507b217843d0d12ecf8b"
name = "WB Checkout Address+"
application_url = "https://phpstack-1046663-6331029.cloudwaysapps.com/"
embedded = true
handle = "web-checkout-address"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_locations,read_publications,read_orders,read_customers,unauthenticated_read_customers,unauthenticated_write_customers,unauthenticated_read_customer_tags"

[auth]
redirect_urls = [
    "https://phpstack-1046663-6331029.cloudwaysapps.com/auth/callback",
    "https://phpstack-1046663-6331029.cloudwaysapps.com/auth/shopify/callback",
    "https://phpstack-1046663-6331029.cloudwaysapps.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false