# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5835e54be9d507b217843d0d12ecf8b"
name = "WB Checkout Address+"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
